/* Telepatch — service worker.

   Everything that touches the network or the token happens here, and
   nowhere else. Two reasons, both load-bearing:

   A content script runs in the page's origin, so its fetches are subject
   to that page's Content-Security-Policy. Plenty of sites set a strict
   connect-src, and saving from those pages would fail for reasons the
   reader could never diagnose. The worker has the extension's own origin
   and its declared host permissions, so api.telegra.ph is always reachable.

   And the token is the whole identity. Keeping it here means it is never
   in the DOM of a page you happen to be visiting, never in a variable a
   content script holds, and never anywhere a site could reach even if the
   isolated world leaked. */

const API = "https://api.telegra.ph/";

// The line /site writes at the foot of an index so it can find the page
// again. It is how a collection is recognised, here and in bot.py.
const MARK = "Index generated by Telepatch.";
const SEP = " — ";

async function telegraph(method, params) {
  const res = await fetch(API + method, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(params)
  });

  if (!res.ok) throw new Error("Telegraph is not answering (" + res.status + ")");

  const data = await res.json();
  if (!data.ok) throw new Error(data.error || "Telegraph refused that");
  return data.result;
}

/* ---------- the master post ---------- */

const textOf = node =>
  typeof node === "string" ? node : (node.children || []).map(textOf).join("");

const isMarker = node =>
  node && node.tag === "p" && textOf(node).trim().startsWith(MARK);

/* An index is prose, then a list, then prose, then the marker line. The
   marker is carried across untouched rather than rebuilt, because it also
   holds the site's byline mode and anything else /site chose to record
   there. Rewriting it from here would quietly drop settings this
   extension has never heard of. */
function splitMaster(content) {
  const nodes = (content || []).filter(n => n && typeof n === "object");
  const marker = nodes.find(isMarker) || null;
  const rest = nodes.filter(n => n !== marker);

  const at = rest.findIndex(n => n.tag === "ul");

  if (at === -1) {
    return { head: rest, list: { tag: "ul", children: [] }, foot: [], marker };
  }
  return { head: rest.slice(0, at), list: rest[at], foot: rest.slice(at + 1), marker };
}

const hrefsIn = node => {
  const found = [];
  const walk = n => {
    if (!n || typeof n !== "object") return;
    if (n.tag === "a" && n.attrs && n.attrs.href) found.push(n.attrs.href);
    (n.children || []).forEach(walk);
  };
  walk(node);
  return found;
};

/* ---------- collections ---------- */

const store = {
  async all() {
    const { collections } = await chrome.storage.local.get("collections");
    return collections || [];
  },
  async put(list) {
    await chrome.storage.local.set({ collections: list });
  }
};

/* One token can own several indexes. Rather than ask somebody to find a
   path, read the account and recognise them: getPageList needs the token,
   which is exactly why a visitor could never do this to you. */
async function discover(token) {
  const account = await telegraph("getAccountInfo", {
    access_token: token,
    fields: JSON.stringify(["short_name", "author_name"])
  });

  const { pages } = await telegraph("getPageList", {
    access_token: token, limit: 200
  });

  const found = [];

  // Sequential on purpose: a burst of parallel requests against a free
  // API on somebody else's behalf is a bad way to introduce yourself.
  for (const page of pages || []) {
    const full = await telegraph("getPage", {
      path: page.path, return_content: "true"
    });

    if ((full.content || []).some(isMarker)) {
      found.push({ path: full.path, title: full.title });
    }
  }

  return { name: account.short_name || account.author_name || "Telepatch", found };
}

/* ---------- actions ---------- */

const cache = new Map();

async function master(path, fresh) {
  const hit = cache.get(path);
  if (!fresh && hit && Date.now() - hit.at < 60000) return hit.page;

  const page = await telegraph("getPage", { path, return_content: "true" });
  cache.set(path, { page, at: Date.now() });
  return page;
}

async function lookup({ path, url }) {
  const page = await master(path);
  const saved = hrefsIn({ children: page.content }).some(href => href === url);
  return { saved, title: page.title };
}

async function save({ id, url, title, cats, note }) {
  const collections = await store.all();
  const collection = collections.find(c => c.id === id);

  if (!collection) throw new Error("That collection is no longer set up");

  const page = await master(collection.path, true);
  const { head, list, foot, marker } = splitMaster(page.content);

  const children = [{ tag: "a", attrs: { href: url }, children: [title] }];

  // Dated today so it sorts newest. No reading time: the length of
  // somebody else's page is not ours to claim.
  let meta = SEP + new Date().toISOString().slice(0, 10);
  if (cats.length) meta += " · " + cats.join(", ");
  children.push(meta);

  if (note) children.push({ tag: "br" }, note);

  list.children = list.children || [];
  list.children.unshift({ tag: "li", children });

  const content = [...head, list, ...foot];
  if (marker) content.push(marker);

  // editPage replaces a page wholesale, so the author fields have to be
  // handed back or they are cleared.
  await telegraph("editPage", {
    access_token: collection.token,
    path: collection.path,
    title: page.title,
    content: JSON.stringify(content),
    author_name: page.author_name || "",
    author_url: page.author_url || ""
  });

  cache.delete(collection.path);
  return { title: page.title };
}

async function connect({ token }) {
  const clean = (token || "").trim();
  if (!/^[0-9a-f]{60}$/.test(clean)) {
    throw new Error("That does not look like a Telegraph token");
  }

  const { name, found } = await discover(clean);
  if (!found.length) {
    throw new Error("No collection on that account yet — run /site in the bot first");
  }

  const collections = await store.all();

  for (const page of found) {
    const id = clean.slice(0, 8) + ":" + page.path;
    if (collections.some(c => c.id === id)) continue;
    collections.push({ id, label: page.title, who: name, token: clean, path: page.path });
  }

  await store.put(collections);
  return { added: found.length };
}

async function forget({ id }) {
  await store.put((await store.all()).filter(c => c.id !== id));
  return {};
}

// The panel is never told a token, only what it needs to draw a list.
async function collections() {
  return (await store.all()).map(c => ({ id: c.id, label: c.label, who: c.who, path: c.path }));
}

const ACTIONS = { collections, connect, forget, save, lookup };

chrome.runtime.onMessage.addListener((msg, sender, reply) => {
  const action = ACTIONS[msg && msg.type];

  if (!action) return false;

  action(msg)
    .then(result => reply({ ok: true, result }))
    .catch(error => reply({ ok: false, error: error.message }));

  return true;   // the reply is coming later
});

// Clicking the toolbar button is the same gesture as the floating one.
chrome.action.onClicked.addListener(tab => {
  if (tab.id != null) chrome.tabs.sendMessage(tab.id, { type: "toggle" }).catch(() => {});
});
