/* Telepatch — service worker.

   Everything that touches the network or the token happens here, and
   nowhere else. Two reasons, both load-bearing:

   A content script runs in the page's origin, so its fetches are subject
   to that page's Content-Security-Policy. Plenty of sites set a strict
   connect-src, and saving from those pages would fail for reasons the
   reader could never diagnose. The worker has the extension's own origin
   and its declared host permissions, so api.telegra.ph is always reachable.

   And the token is the whole identity. Keeping it here means it is never
   in the DOM of a page you happen to be visiting, never in a variable a
   content script holds, and never anywhere a site could reach even if the
   isolated world leaked. */

const API = "https://api.telegra.ph/";

// The line /site writes at the foot of an index so it can find the page
// again. It is how a collection is recognised, here and in bot.py.
const MARK = "Index generated by Telepatch.";

// Telegraph cannot delete a page, so a collection taken out of service is
// marked instead. /retire replaces the marker outright, but a page retired
// by hand in the Telegraph editor may carry both lines - so this is
// checked across the whole page rather than only on the marker paragraph.
const RETIRED = "Retired Telepatch index.";

const SEP = " — ";

async function telegraph(method, params) {
  const res = await fetch(API + method, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(params)
  });

  if (!res.ok) throw new Error("Telegraph is not answering (" + res.status + ")");

  const data = await res.json();
  if (!data.ok) throw new Error(data.error || "Telegraph refused that");
  return data.result;
}

/* ---------- the master post ---------- */

const textOf = node =>
  typeof node === "string" ? node : (node.children || []).map(textOf).join("");

const isMarker = node =>
  node && node.tag === "p" && textOf(node).trim().startsWith(MARK);

const isRetired = content =>
  (content || []).some(node => textOf(node).includes(RETIRED));

/* An index is prose, then a list, then prose, then the marker line. The
   marker is carried across untouched rather than rebuilt, because it also
   holds the site's byline mode and anything else /site chose to record
   there. Rewriting it from here would quietly drop settings this
   extension has never heard of. */
function splitMaster(content) {
  const nodes = (content || []).filter(n => n && typeof n === "object");
  const marker = nodes.find(isMarker) || null;
  const rest = nodes.filter(n => n !== marker);

  const at = rest.findIndex(n => n.tag === "ul");

  if (at === -1) {
    return { head: rest, list: { tag: "ul", children: [] }, foot: [], marker };
  }
  return { head: rest.slice(0, at), list: rest[at], foot: rest.slice(at + 1), marker };
}

const hrefsIn = node => {
  const found = [];
  const walk = n => {
    if (!n || typeof n !== "object") return;
    if (n.tag === "a" && n.attrs && n.attrs.href) found.push(n.attrs.href);
    (n.children || []).forEach(walk);
  };
  walk(node);
  return found;
};

/* ---------- collections ---------- */

const store = {
  async all() {
    const { collections } = await chrome.storage.local.get("collections");
    return collections || [];
  },
  async put(list) {
    await chrome.storage.local.set({ collections: list });
  }
};

/* One token can own several indexes. Rather than ask somebody to find a
   path, read the account and recognise them: getPageList needs the token,
   which is exactly why a visitor could never do this to you. */
async function discover(token) {
  const account = await telegraph("getAccountInfo", {
    access_token: token,
    fields: JSON.stringify(["short_name", "author_name"])
  });

  const { pages } = await telegraph("getPageList", {
    access_token: token, limit: 200
  });

  const found = [];

  /* Connecting is the first thing anyone does, and reading a page at a
     time made it the slowest. A few at once is enough to hide the
     latency; a burst of two hundred against a free API on somebody
     else's behalf is a bad way to introduce yourself, and the limits are
     not documented. */
  const queue = [...(pages || [])];

  const worker = async () => {
    while (queue.length) {
      const page = queue.shift();

      try {
        const full = await telegraph("getPage", {
          path: page.path, return_content: "true"
        });

        if ((full.content || []).some(isMarker) && !isRetired(full.content)) {
          found.push({ path: full.path, title: full.title });
        }

      } catch (err) {
        // One unreadable page is not a reason to refuse the account.
      }
    }
  };

  await Promise.all(
    Array.from({ length: Math.min(6, queue.length) }, worker)
  );

  // getPageList is newest first; the workers finish out of order.
  const order = new Map((pages || []).map((p, i) => [p.path, i]));
  found.sort((a, b) => order.get(a.path) - order.get(b.path));

  return { name: account.short_name || account.author_name || "Telepatch", found };
}

/* ---------- actions ---------- */

const cache = new Map();

async function master(path, fresh) {
  const hit = cache.get(path);
  if (!fresh && hit && Date.now() - hit.at < 60000) return hit.page;

  const page = await telegraph("getPage", { path, return_content: "true" });
  cache.set(path, { page, at: Date.now() });
  return page;
}

async function lookup({ path, url }) {
  const page = await master(path);
  const saved = hrefsIn({ children: page.content }).some(href => href === url);
  return { saved, title: page.title };
}

/* One entry at the top of the list, in the shape the bot writes, so /site
   keeps it on the next rebuild and the website reads it as an ordinary
   item. Minutes are omitted for a saved page - the length of somebody
   else's writing is not ours to claim - and included for a post, where we
   counted the words ourselves. */
async function spliceEntry(collection, { url, title, cats, note, minutes }) {
  const page = await master(collection.path, true);
  const { head, list, foot, marker } = splitMaster(page.content);

  const children = [{ tag: "a", attrs: { href: url }, children: [title] }];

  let meta = SEP + new Date().toISOString().slice(0, 10);
  if (minutes) meta += " · " + minutes + " min";
  if (cats.length) meta += " · " + cats.join(", ");
  children.push(meta);

  if (note) children.push({ tag: "br" }, note);

  list.children = list.children || [];
  list.children.unshift({ tag: "li", children });

  const content = [...head, list, ...foot];
  if (marker) content.push(marker);

  // editPage replaces a page wholesale, so the author fields have to be
  // handed back or they are cleared.
  await telegraph("editPage", {
    access_token: collection.token,
    path: collection.path,
    title: page.title,
    content: JSON.stringify(content),
    author_name: page.author_name || "",
    author_url: page.author_url || ""
  });

  cache.delete(collection.path);
  return { title: page.title };
}

function collectionFor(collections, id) {
  const found = collections.find(c => c.id === id);
  if (!found) throw new Error("That collection is no longer set up");
  return found;
}

async function save({ id, url, title, cats, note }) {
  const collection = collectionFor(await store.all(), id);
  return spliceEntry(collection, { url, title, cats, note, minutes: 0 });
}

/* ---------- writing ---------- */

const IMAGE_RE = /^(https?:\/\/\S+\.(?:png|jpe?g|gif|webp|svg))(?:\s+(.*))?$/i;

// A single newline inside a block is a line break, not a new block.
const asLines = text => {
  const children = [];
  text.split("\n").forEach((line, i) => {
    if (i) children.push({ tag: "br" });
    children.push(line);
  });
  return children;
};

/* Plain text into Telegraph nodes, using the same markers as /post so that
   what somebody learns in the chat still works here. Blank lines separate
   blocks; a single newline inside one stays a line break. */
function compose(cats, body) {
  const nodes = [];

  // The site reads the first <aside> as the article's categories, which is
  // also what Telegraph renders as a centred subtitle.
  if (cats.length) nodes.push({ tag: "aside", children: [cats.join(", ")] });

  for (const block of String(body).replace(/\r\n?/g, "\n").split(/\n{2,}/)) {
    const text = block.trim();
    if (!text) continue;

    // Telegraph allows only h3 and h4, and the title holds the level above.
    const heading = /^(#{1,3})\s+([\s\S]*)$/.exec(text);
    if (heading) {
      nodes.push({
        tag: heading[1].length >= 3 ? "h4" : "h3",
        children: [heading[2].trim()]
      });
      continue;
    }

    if (text.startsWith(">")) {
      nodes.push({
        tag: "blockquote",
        children: asLines(text.replace(/^>[ \t]?/gm, "").trim())
      });
      continue;
    }

    const image = IMAGE_RE.exec(text);
    if (image) {
      const figure = { tag: "figure", children: [{ tag: "img", attrs: { src: image[1] } }] };
      if (image[2]) figure.children.push({ tag: "figcaption", children: [image[2].trim()] });
      nodes.push(figure);
      continue;
    }

    nodes.push({ tag: "p", children: asLines(text) });
  }

  return nodes;
}

/* The opening prose, for the line under the title in the index. Headings,
   quotes and pictures are skipped: an excerpt should read like the start
   of the piece, not like its furniture. */
function summarise(body) {
  for (const block of String(body).replace(/\r\n?/g, "\n").split(/\n{2,}/)) {
    const text = block.trim();
    if (!text || /^[#>]/.test(text) || IMAGE_RE.test(text)) continue;

    const flat = text.replace(/\s+/g, " ");
    return flat.length > 220 ? flat.slice(0, 219).trimEnd() + "…" : flat;
  }
  return "";
}

async function publish({ id, title, cats, body }) {
  const collection = collectionFor(await store.all(), id);

  const clean = (title || "").trim();
  if (!clean) throw new Error("A post needs a title");
  if (!String(body).trim()) throw new Error("Nothing written yet");

  // author_name is left out on purpose: Telegraph then uses the account's
  // own, which is the one the site already shows.
  const page = await telegraph("createPage", {
    access_token: collection.token,
    title: clean,
    content: JSON.stringify(compose(cats, body))
  });

  const words = String(body).trim().split(/\s+/).filter(Boolean).length;

  await spliceEntry(collection, {
    url: "/" + page.path,          // relative, exactly as the bot writes it
    title: clean,
    cats,
    note: summarise(body),
    minutes: Math.max(1, Math.round(words / 200))
  });

  return { url: page.url, path: page.path };
}

async function connect({ token }) {
  const clean = (token || "").trim();
  if (!/^[0-9a-f]{60}$/.test(clean)) {
    throw new Error("That does not look like a Telegraph token");
  }

  const { name, found } = await discover(clean);
  if (!found.length) {
    throw new Error("No collection on that account yet — run /site in the bot first");
  }

  const collections = await store.all();

  for (const page of found) {
    const id = clean.slice(0, 8) + ":" + page.path;
    if (collections.some(c => c.id === id)) continue;
    collections.push({ id, label: page.title, who: name, token: clean, path: page.path });
  }

  await store.put(collections);
  return { added: found.length };
}

async function forget({ id }) {
  await store.put((await store.all()).filter(c => c.id !== id));
  return {};
}

// The panel is never told a token, only what it needs to draw a list.
async function collections() {
  return (await store.all()).map(c => ({ id: c.id, label: c.label, who: c.who, path: c.path }));
}

const ACTIONS = { collections, connect, forget, save, lookup, publish };

chrome.runtime.onMessage.addListener((msg, sender, reply) => {
  const action = ACTIONS[msg && msg.type];

  if (!action) return false;

  action(msg)
    .then(result => reply({ ok: true, result }))
    .catch(error => reply({ ok: false, error: error.message }));

  return true;   // the reply is coming later
});

// Clicking the toolbar button is the same gesture as the floating one.
chrome.action.onClicked.addListener(tab => {
  if (tab.id != null) chrome.tabs.sendMessage(tab.id, { type: "toggle" }).catch(() => {});
});
