"""
Shared fixtures.

bot.py reads TELEGRAM_TOKEN at import time and builds nothing else, so it
can be imported directly once the environment has one. Nothing here touches
the network: every function under test is pure.
"""

import importlib.util
import os
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(scope="session")
def bot():
    # Shaped like a BotFather token because bot.py now validates it at
    # import, and refuses to start on anything that is not.
    os.environ.setdefault(
        "TELEGRAM_TOKEN", "123456789:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    )

    spec = importlib.util.spec_from_file_location("telepatch_bot", ROOT / "bot.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["telepatch_bot"] = module
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------- content

def p(text):
    return {"tag": "p", "children": [text]}


def a(href, text):
    return {"tag": "a", "attrs": {"href": href}, "children": [text]}


def li(href, title, meta="", excerpt=""):
    children = [a(href, title)]
    if meta:
        children.append(meta)
    if excerpt:
        children += [{"tag": "br"}, excerpt]
    return {"tag": "li", "children": children}


@pytest.fixture
def primary():
    """A live primary index, with prose above and below the list."""
    return [
        p("An introduction the publisher wrote."),
        {"tag": "ul", "children": [
            li("/One-07-28", "One", " — 2026-07-28 · 2 min · tin", "The first."),
            li("/Two-07-28", "Two", " — 2026-07-27 · 3 min · tin, trade", "The second."),
        ]},
        p("A footer the publisher wrote."),
        p("Index generated by Telepatch. byline=separate"),
    ]


@pytest.fixture
def curated():
    """A curated collection: same shape, one extra field on the marker."""
    return [
        {"tag": "ul", "children": [
            li("/Filed-07-28", "Filed", " — 2026-07-28 · 1 min"),
            li("https://telegra.ph/Also-Filed-07-28", "Also filed", " — 2026-07-28"),
            li("https://github.com/babbworks/telepatch", "A repo", " — 2026-07-28 · code"),
        ]},
        p("Index generated by Telepatch. byline=linked collection=extra"),
    ]


@pytest.fixture
def retired():
    """Retired by /retire, which replaces the marker outright."""
    return [
        {"tag": "ul", "children": [li("/Stranded-07-28", "Stranded")]},
        p("Retired Telepatch index."),
    ]


@pytest.fixture
def hand_retired():
    """
    Retired by hand in the Telegraph editor, which is documented and
    supported: the original marker is still there and the retirement line
    was added beside it. Everything that looks for an index has to notice
    the second line, not just the first.
    """
    return [
        {"tag": "ul", "children": [li("/Hand-Stranded-07-28", "Hand stranded")]},
        p("Index generated by Telepatch. byline=linked collection=extra"),
        p("Retired Telepatch index."),
    ]


@pytest.fixture
def legacy():
    """An index written before byline= or collection= existed."""
    return [
        p("Older prose."),
        {"tag": "ul", "children": [li("/Old-07-01", "Old")]},
        p("Index generated by Telepatch."),
    ]


@pytest.fixture
def article():
    return [
        {"tag": "aside", "children": ["tin, industry"]},
        {"tag": "blockquote", "children": ["What the ledgers say."]},
        p("The price held steady for most of the decade. " * 30),
    ]


# ------------------------------------------------------------- telegram

class Entity:
    """Enough of a MessageEntity for the carrier reader."""

    def __init__(self, url, kind="text_link"):
        self.type = kind
        self.url = url


class Message:
    def __init__(self, entities=None, reply_to=None, text=""):
        self.entities = entities or []
        self.reply_to_message = reply_to
        self.text = text
        self.reply_markup = None


class Update:
    def __init__(self, message):
        self.message = message


class Context:
    def __init__(self, args=None):
        self.args = args or []
